services:
  - type: web
    name: xapi
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn xapi.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PORT
        value: 8000
